# -*- coding: utf-8 -*-
"""nlp_as1_B1121123.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJlG0Nk3_HXw9qM7iBv0eKILK98769L8

# 作業1：Word Analogy with Word Embeddings

## Part I: Data Pre-processing

### steps
*   下載 Google Analogy 資料集
*   讀入資料集，使其變成 list 的形式
*   將資料處理成 pd.DataFrame 的形式
"""

# 0. 引入套件

import pandas as pd

# 1. 下載 Google Analogy 資料集

!wget http://download.tensorflow.org/data/questions-words.txt

# 2. 讀入資料集，使其變成 list 的形式

file_name = "questions-words"
with open(f"{file_name}.txt", "r") as f:
    data = f.read().splitlines() # 將每一行的資料分割成 list 的元素

# 3. 印出前 10 筆資料，確認資料集的內容

for entry in data[:10]:
    print(entry)

# 4. TODO1: 將資料處理成 pd.DataFrame 的形式
# 請將資料 (`questions-words.txt`) 處理成 pd.DataFrame
# 請注意，`questions-words.txt` 中前五次出現的 ": " 表示 `semantic` 類別 (語義相似性)，
# 而其餘九次則屬於 `syntatic` 類別 (語法相似性)。
# 請參考第5格來處理資料，並將結果存成 `df` 變數。

questions, categories, sub_categories = [], [], []
# ----------------------
# Write your code here.
# ----------------------
colon_count = 0
current_category = ""
current_subcategory = ""

# 遇到以 : 開頭的行就視為子類別（SubCategory），並計算出現的次數來決定主類別（Category）是 semantic 還是 syntactic
for line in data:
    line = line.strip() # 移除頭尾空白與換行符號

    # 檢查是否為標記子類別的行
    if line.startswith(":"):
        colon_count += 1
        # dataset 前 5 個是 semantic，之後的是 syntactic
        if colon_count <= 5:
            current_category = "semantic"
        else:
            current_category = "syntactic"
        current_subcategory = line
    else:
        questions.append(line) # 在 list 最後面新增一個元素
        categories.append(current_category)
        sub_categories.append(current_subcategory)

# 5. Create the dataframe
# 其中 questions, categories, sub_categories 皆為 list 的形式

df = pd.DataFrame(
    {
        "Question": questions,
        "Category": categories,
        "SubCategory": sub_categories,
    }
)

# 6. 你可以觀察一下資料集的前幾筆資料，確認是否正確處理

df.to_csv(f"{file_name}.csv", index=False) # 將資料存成 csv 檔
df.head()

"""## Part II: Use pre-trained word embeddings
- After finish Part I, you can run Part II code blocks only.

### steps
*   讀入剛剛處理好的 csv 檔案
*   載入預訓練好的詞向量模型 (pre-trained word embeddings)
*   進行 word analogy 預測
*   模型評估
*   使用 t-SNE 畫出 SUB_CATEGORY `: family` 的詞在 2D 空間的分佈
"""

# 0. 引入套件
!pip install gensim # 安裝 gensim 套件
import pandas as pd
import numpy as np
import gensim.downloader # 這樣這裡才不會報錯
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE


import pandas as pd
import numpy as np
import gensim
import tqdm
import matplotlib
import sklearn

print(f"pandas 版本: {pd.__version__}")
print(f"numpy 版本: {np.__version__}")
print(f"gensim 版本: {gensim.__version__}")
print(f"tqdm 版本: {tqdm.__version__}")
print(f"matplotlib 版本: {matplotlib.__version__}")
print(f"scikit-learn (sklearn) 版本: {sklearn.__version__}")

# 7. 讀入剛剛處理好的 csv 檔案

data = pd.read_csv("questions-words.csv")

# 8. 載入預訓練好的詞向量模型 (pre-trained word embeddings)

# try other models.
# https://radimrehurek.com/gensim/models/word2vec.html#pretrained-models

# Load the pre-trained model (using GloVe vectors here)
# GloVe (Global Vectors) 的訓練原理是基於「全域詞彙共現矩陣」的分解，這與 Word2Vec 的 CBOW 或 Skip-gram（預測機制）本質上是不同的演算法。
model = gensim.downloader.load("glove-wiki-gigaword-100")
print("The Gensim model loaded successfully!")

# 9. TODO2: 進行 word analogy 預測，並保留 gold answers (word_D)

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = [] # 因為等等要對答案進行評估，所以我們需要保留 gold answers (word_D)

for analogy in tqdm(data["Question"]):
      # Use pre-trained word embeddings for getting predictions of the analogy task.
      # You should also preserve the gold answers during iterations for evaluations later.
      """ Hints
      # Unpack the analogy (e.g., "man", "woman", "king", "queen")
      # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
      # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L778
      # Mikolov et al., 2013: big - biggest and small - smallest
      # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
      """
      # ----------------------
      # Write your code here.
      # ----------------------
      # 先將題目拆解為 4 個單字並轉小寫 (a, b, c, d)
      a, b, c, d = analogy.lower().split()

      # 保留標準答案
      golds.append(d)

      # Gensim 的套件: 在 上面 source 778 行 (對應公式：b + c - a)
      preds.append(model.most_similar(positive=[b, c], negative=[a], topn=1)[0][0])
'''
positive=[b, c]：對應公式裡的加項（加上單字 B 與 C 的向量）。
negative=[a]：對應公式裡的減項（減去單字 A 的向量）。
topn=1：因為我們只需要預測出最接近的 1 個答案（也就是預測的 D），將它設為 1 可以避免回傳多餘的結果。
[0][0]：most_similar 的回傳格式是一個包含 Tuple 的 List，例如 [('queen', 0.769)]。
透過 [0][0] 就能直接把字串提取出來存進 preds 裡。
'''

# 10. 進行模型評估 (Gemini provided)

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    # 強制將 numpy array 內的字串轉為小寫再做比較
    gold_lower = np.char.lower(gold.astype(str))
    pred_lower = np.char.lower(pred.astype(str))
    return np.mean(gold_lower == pred_lower)

golds_np, preds_np = np.array(golds), np.array(preds)

# === 整體準確率 ===
overall_acc = calculate_accuracy(golds_np, preds_np)
print(f"【Overall Accuracy】: {overall_acc * 100:.2f}%\n" + "="*45)

# === Evaluation: categories ===
print("【Category Performance】")
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    # 使用 :<10 讓字串向左對齊，佔用 10 個字元寬度
    print(f"Category: {category:<10} | Accuracy: {acc_cat * 100:.2f}%")

print("-" * 45)

# === Evaluation: sub-categories ===
print("【Sub-Category Performance】")
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    # 將前面的 ': ' 濾掉讓畫面更乾淨，並設定對齊寬度
    clean_subcat_name = sub_category.replace(": ", "")
    print(f"Sub-Category: {clean_subcat_name:<30} | Accuracy: {acc_subcat * 100:.2f}%")

# 11. TODO3: 使用 t-SNE 畫出 SUB_CATEGORY `: family` 的詞在 2D 空間的分佈

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# ----------------------
# Write your code here.
# ----------------------
family_words = set()
# 篩選出 family 類別的題目
mask = data["SubCategory"] == SUB_CATEGORY

for question in data[mask]["Question"]:
    # 將題目拆解成單字，轉為小寫並加入集合中確保不重複
    family_words.update(question.lower().split())

valid_words = []
word_embeddings = []

# 取出這些單字在預訓練模型中的 100 維詞向量
for word in family_words:
    if word in model:
        valid_words.append(word)
        word_embeddings.append(model[word])

word_embeddings = np.array(word_embeddings)

# -----------------------------------------------------------

'''
Gemini provided:
perplexity : 每個資料點在降維時，所關注的『有效鄰居數量』或是『視野大小』
較小的 Perplexity（例如 5）：模型視野很窄，每個點只會參考離自己最近的幾個鄰居。
這會讓降維後的圖形非常強調「局部結構」（Local Structure），資料點可能會碎裂成很多密集的小群體。

較大的 Perplexity（例如 30 到 50）：模型視野較廣，會同時考慮較遠的點。
這有助於捕捉資料的「全局結構」（Global Structure），整體的群聚分佈會比較宏觀、連續。

t-SNE 有一個硬性規定：perplexity 的值必須「嚴格小於」樣本的總數量。
所以改成了 perplexity_value = min(30, len(valid_words) - 1)。
這行的意思是：如果單字數量夠多，就用預設的 30；
如果單字數量不夠，就把 perplexity 自動調降到總單字數減 1，藉此保護程式不報錯。
'''
perplexity_value = min(30, len(valid_words) - 1)

tsne = TSNE(n_components=2, random_state=42, perplexity=30)
word_embeddings_2d = tsne.fit_transform(word_embeddings)

# Plotting the words in 2D space
plt.figure(figsize=(12, 10))
plt.scatter(word_embeddings_2d[:, 0], word_embeddings_2d[:, 1])

# Annotate points with words
for i, word in enumerate(valid_words):
    plt.annotate(
        word, (word_embeddings_2d[i, 0], word_embeddings_2d[i, 1]), fontsize=9
    )

plt.title("Word Relationships from Google Analogy Task")
# 必須先存檔 (savefig) 再顯示 (show)，否則存出來的圖片會是全白的！
plt.savefig("word_relationships.png", bbox_inches="tight")
plt.show()

"""## Part III: Train your own word embeddings

### Get the latest English Wikipedia articles and do sampling.
- Usually, we start from Wikipedia dump (https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). However, the downloading step will take very long. Also, the cleaning step for the Wikipedia corpus ([`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus)) will take much time. Therefore, we provide cleaned files for you.

### steps
* Download the file
* Sample `20%` Wikipedia articles
* Train your own word embeddings with the sampled articles
* 使用 t-SNE 畫出 SUB_CATEGORY `: family` 的詞在 2D 空間的分佈
"""

# 12-1. Download the split Wikipedia files
# Each file contain 562365 lines (articles).
!gdown --id 1jiu9E1NalT2Y8EIuWNa1xf2Tw1f1XuGd -O wiki_texts_part_0.txt.gz
!gdown --id 1ABblLRd9HXdXvaNv8H9fFq984bhnowoG -O wiki_texts_part_1.txt.gz
!gdown --id 1z2VFNhpPvCejTP5zyejzKj5YjI_Bn42M -O wiki_texts_part_2.txt.gz
!gdown --id 1VKjded9BxADRhIoCzXy_W8uzVOTWIf0g -O wiki_texts_part_3.txt.gz
!gdown --id 16mBeG26m9LzHXdPe8UrijUIc6sHxhknz -O wiki_texts_part_4.txt.gz

# 12-2. Download the split Wikipedia files
# Each file contain 562365 lines (articles), except the last file.
!gdown --id 17JFvxOH-kc-VmvGkhG7p3iSZSpsWdgJI -O wiki_texts_part_5.txt.gz
!gdown --id 19IvB2vOJRGlrYulnTXlZECR8zT5v550P -O wiki_texts_part_6.txt.gz
!gdown --id 1sjwO8A2SDOKruv6-8NEq7pEIuQ50ygVV -O wiki_texts_part_7.txt.gz
!gdown --id 1s7xKWJmyk98Jbq6Fi1scrHy7fr_ellUX -O wiki_texts_part_8.txt.gz
!gdown --id 17eQXcrvY1cfpKelLbP2BhQKrljnFNykr -O wiki_texts_part_9.txt.gz
!gdown --id 1J5TAN6bNBiSgTIYiPwzmABvGhAF58h62 -O wiki_texts_part_10.txt.gz

# 13. Extract the downloaded wiki_texts_parts files.
!gunzip -k wiki_texts_part_*.gz

# 14. Combine the extracted wiki_texts_parts files.
!cat wiki_texts_part_*.txt > wiki_texts_combined.txt

# 15. Check the first ten lines of the combined file
!head -n 10 wiki_texts_combined.txt

"""Please note that we used the default parameters of [`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus) for cleaning the Wiki raw file. Thus, words with one character were discarded."""

# 16. # TODO4: Sample `20%` Wikipedia articles
# Now you need to do sampling because the corpus is too big.
# You can further perform analysis with a greater sampling ratio.(Gemini provided)

import random

wiki_txt_path = "wiki_texts_combined.txt"
output_path = "wiki_texts_sampled.txt"

# 定義一個使用 yield 的 generator (生成器)
def sample_lines(file_obj, ratio=0.2):
    for line in file_obj:
        # random.random() 會產生 0.0 ~ 1.0 的隨機浮點數
        # 小於 0.2 就代表有 20% 的機率會被抽中並 yield 出來
        if random.random() < ratio:
            yield line

with open(wiki_txt_path, "r", encoding="utf-8") as f:
    with open(output_path, "w", encoding="utf-8") as output_file:

        # Write your code here
        # 透過 generator 逐行取得抽樣後的文章，並寫入新檔案
        for sampled_line in sample_lines(f, ratio=0.2):
            output_file.write(sampled_line)

# 17. TODO5: Train your own word embeddings with the sampled articles
# https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec
# Hint: You should perform some pre-processing before training.

# use below link to pre-processing before training.
# https://tedboy.github.io/nlps/generated/generated/gensim.utils.simple_preprocess.html

import os
import gensim
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence
from gensim.utils import simple_preprocess

sampled_file_path = "wiki_texts_sampled.txt"
preprocessed_file_path = "wiki_texts_preprocessed.txt"

# --- 1. 一次性完成前處理 (大幅節省後續 Epochs 的重複計算時間) ---
print("步驟 1：開始進行資料前處理...")
with open(sampled_file_path, "r", encoding="utf-8") as fin:
    with open(preprocessed_file_path, "w", encoding="utf-8") as fout:
        for line in fin:
            # 根據截圖中的文件說明，明確加入 simple_preprocess 的參數
            # deacc=False: 不移除重音符號 (如果處理純英文或中文通常沒差)
            # min_len=2: 捨棄長度小於 2 的單字 (例如 a, I 等單一字母)
            # max_len=15: 捨棄長度大於 15 的單字 (通常是無意義的亂碼或超長連字)
            tokens = simple_preprocess(line, deacc=False, min_len=2, max_len=15)

            if tokens:  # 確保不是空行
                fout.write(" ".join(tokens) + "\n")

print("前處理完成！已儲存為:", preprocessed_file_path)

# --- 2. 使用 Gensim 內建的 LineSentence 讀取資料 ---
sentences = LineSentence(preprocessed_file_path)

import gensim
print(f"Gensim version: {gensim.__version__}")

import time  # 引入時間模組

# --- 3. 訓練 Word2Vec 模型 ---
print("步驟 2：開始訓練 Word2Vec model ...")

# 自動偵測目前的最大 CPU 核心數
max_workers = os.cpu_count() or 4
print(f"偵測到可使用 {max_workers} 個 CPU 核心進行加速")


# === 紀錄開始時間 ===
start_time = time.time()

my_model = Word2Vec(
    sentences=sentences, # 餵給模型的文本資料，前面已經處理過
    vector_size=100,     # embedding the words into a 100-dimensional vector space
    window=5,            # context window of 5 words
    min_count=5,
    workers=max_workers, # 最大化利用 CPU 資源
    epochs=5 ,            # 預設為 5，如果只想隨便測一下可以改成 3 (會更快但準確率下降)

    # --- 加速參數 ---
    sg=0,           # 使用 CBOW (sg=0) 通常比 Skip-gram (sg=1) 快非常多
    negative=5,     # 負採樣，減少每一步的運算量     補充: 實務上負採樣對罕見詞的表現通常較好。
    hs=0,           # 關閉 Hierarchical Softmax (與 Negative Sampling 二選一)
    sample=1e-3,    # 高頻詞下採樣：自動減少「的、是、在」等無意義高頻詞的訓練頻率
    # ----------------
)

# === 紀錄結束時間並計算差值 ===
end_time = time.time()
training_duration = end_time - start_time
hours, remainder = divmod(training_duration, 3600)
minutes, seconds = divmod(remainder, 60)
print(f"模型訓練完成！")
print(f"本次訓練總共耗時：{int(hours)} 小時 {int(minutes)} 分鐘 {seconds:.2f} 秒")

# --- 4. 儲存模型以便未來使用 ---
my_model.save("my_wiki_word2vec.model")
print("模型已儲存為 my_wiki_word2vec.model")

# 18. 再次讀入資料（方便同學單獨進行 Part 3）

data = pd.read_csv("questions-words.csv")

# 19. TODO6: Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

for analogy in tqdm(data["Question"]):
      # Use your trained word embeddings for getting predictions of the analogy task.
      # You should also preserve the gold answers during iterations for evaluations later.
      """ Hints
      # Unpack the analogy (e.g., "man", "woman", "king", "queen")
      # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
      # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L778
      # Mikolov et al., 2013: big - biggest and small - smallest
      # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
      """
      # Write your code here
      # 先將題目拆解為 4 個單字並轉小寫 (a, b, c, d)
      a, b, c, d = analogy.lower().split()

      # 保留標準答案
      golds.append(d)

      # Gensim 的套件: 在 source 778 行 (對應公式：b + c - a)
      # preds.append(my_model.most_similar(positive=[b, c], negative=[a], topn=1)[0][0])
      preds.append(my_model.wv.most_similar(positive=[b, c], negative=[a], topn=1)[0][0])

# 10. 進行模型評估 (Gemini provided)

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    # 強制將 numpy array 內的字串轉為小寫再做比較
    gold_lower = np.char.lower(gold.astype(str))
    pred_lower = np.char.lower(pred.astype(str))
    return np.mean(gold_lower == pred_lower)

golds_np, preds_np = np.array(golds), np.array(preds)

# === 整體準確率 ===
overall_acc = calculate_accuracy(golds_np, preds_np)
print(f"【Overall Accuracy】: {overall_acc * 100:.2f}%\n" + "="*45)

# === Evaluation: categories ===
print("【Category Performance】")
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    # 使用 :<10 讓字串向左對齊，佔用 10 個字元寬度
    print(f"Category: {category:<10} | Accuracy: {acc_cat * 100:.2f}%")

print("-" * 45)

# === Evaluation: sub-categories ===
print("【Sub-Category Performance】")
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    # 將前面的 ': ' 濾掉讓畫面更乾淨，並設定對齊寬度
    clean_subcat_name = sub_category.replace(": ", "")
    print(f"Sub-Category: {clean_subcat_name:<30} | Accuracy: {acc_subcat * 100:.2f}%")

import numpy as np
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

# 20. same as 11. TODO3: 使用 t-SNE 畫出 SUB_CATEGORY `: family` 的詞在 2D 空間的分佈

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# --- TODO3 ---
family_words = set()
# 篩選出 family 類別的題目
mask = data["SubCategory"] == SUB_CATEGORY

for question in data[mask]["Question"]:
    # 將題目拆解成單字，轉為小寫並加入集合中確保不重複
    family_words.update(question.lower().split())

valid_words = []
word_embeddings = []

# 取出這些單字在預訓練模型中的 100 維詞向量
for word in family_words:
    if word in my_model.wv:
        valid_words.append(word)
        word_embeddings.append(my_model.wv[word])

word_embeddings = np.array(word_embeddings)
# -----------------------------------
# perplexity = 每個資料點在降維時，所關注的『有效鄰居數量』或是『視野大小』
'''
較小的 Perplexity（例如 5）：模型視野很窄，每個點只會參考離自己最近的幾個鄰居。這會讓降維後的圖形非常強調「局部結構」（Local Structure），資料點可能會碎裂成很多密集的小群體。
較大的 Perplexity（例如 30 到 50）：模型視野較廣，會同時考慮較遠的點。這有助於捕捉資料的「全局結構」（Global Structure），整體的群聚分佈會比較宏觀、連續。

t-SNE 有一個硬性規定：perplexity 的值必須「嚴格小於」樣本的總數量。
所以我改成了 perplexity_value = min(30, len(valid_words) - 1)。
這行的意思是：如果單字數量夠多，就用預設的 30；
如果單字數量不夠，就把 perplexity 自動調降到總單字數減 1，藉此保護程式不報錯。
'''
perplexity_value = min(30, len(valid_words) - 1)
tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity_value)
word_embeddings_2d = tsne.fit_transform(word_embeddings)

# Plotting the words in 2D space
plt.figure(figsize=(12, 10))
plt.scatter(word_embeddings_2d[:, 0], word_embeddings_2d[:, 1])

# Annotate points with words
for i, word in enumerate(valid_words):
    plt.annotate(
        word, (word_embeddings_2d[i, 0], word_embeddings_2d[i, 1]), fontsize=9
    )

plt.title("Word Relationships from Google Analogy Task")
plt.savefig("word_relationships.png", bbox_inches="tight")
plt.show()